// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package serum_dex

import (
	"encoding/binary"
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ConsumeEventsPermissioned is the `ConsumeEventsPermissioned` instruction.
type ConsumeEventsPermissioned struct {
	Limit *uint16

	// [0] = [WRITE] openOrders
	// ··········· OpenOrders; TODO: this is an array
	//
	// [1] = [WRITE] market
	// ··········· market
	//
	// [2] = [WRITE] eventQueue
	// ··········· event queue
	//
	// [3] = [SIGNER] crankAuthority
	// ··········· crank authority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewConsumeEventsPermissionedInstructionBuilder creates a new `ConsumeEventsPermissioned` instruction builder.
func NewConsumeEventsPermissionedInstructionBuilder() *ConsumeEventsPermissioned {
	nd := &ConsumeEventsPermissioned{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetLimit sets the "limit" parameter.
func (inst *ConsumeEventsPermissioned) SetLimit(limit uint16) *ConsumeEventsPermissioned {
	inst.Limit = &limit
	return inst
}

// SetOpenOrdersAccount sets the "openOrders" account.
// OpenOrders; TODO: this is an array
func (inst *ConsumeEventsPermissioned) SetOpenOrdersAccount(openOrders ag_solanago.PublicKey) *ConsumeEventsPermissioned {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(openOrders).WRITE()
	return inst
}

// GetOpenOrdersAccount gets the "openOrders" account.
// OpenOrders; TODO: this is an array
func (inst *ConsumeEventsPermissioned) GetOpenOrdersAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetMarketAccount sets the "market" account.
// market
func (inst *ConsumeEventsPermissioned) SetMarketAccount(market ag_solanago.PublicKey) *ConsumeEventsPermissioned {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(market).WRITE()
	return inst
}

// GetMarketAccount gets the "market" account.
// market
func (inst *ConsumeEventsPermissioned) GetMarketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetEventQueueAccount sets the "eventQueue" account.
// event queue
func (inst *ConsumeEventsPermissioned) SetEventQueueAccount(eventQueue ag_solanago.PublicKey) *ConsumeEventsPermissioned {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(eventQueue).WRITE()
	return inst
}

// GetEventQueueAccount gets the "eventQueue" account.
// event queue
func (inst *ConsumeEventsPermissioned) GetEventQueueAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetCrankAuthorityAccount sets the "crankAuthority" account.
// crank authority
func (inst *ConsumeEventsPermissioned) SetCrankAuthorityAccount(crankAuthority ag_solanago.PublicKey) *ConsumeEventsPermissioned {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(crankAuthority).SIGNER()
	return inst
}

// GetCrankAuthorityAccount gets the "crankAuthority" account.
// crank authority
func (inst *ConsumeEventsPermissioned) GetCrankAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}

func (inst ConsumeEventsPermissioned) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.TypeIDFromUint32(Instruction_ConsumeEventsPermissioned, binary.LittleEndian),
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ConsumeEventsPermissioned) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ConsumeEventsPermissioned) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Limit == nil {
			return errors.New("Limit parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.OpenOrders is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Market is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.EventQueue is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.CrankAuthority is not set")
		}
	}
	return nil
}

func (inst *ConsumeEventsPermissioned) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ConsumeEventsPermissioned")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Limit", *inst.Limit))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("    openOrders", inst.AccountMetaSlice[0]))
						accountsBranch.Child(ag_format.Meta("        market", inst.AccountMetaSlice[1]))
						accountsBranch.Child(ag_format.Meta("    eventQueue", inst.AccountMetaSlice[2]))
						accountsBranch.Child(ag_format.Meta("crankAuthority", inst.AccountMetaSlice[3]))
					})
				})
		})
}

func (obj ConsumeEventsPermissioned) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Limit` param:
	err = encoder.Encode(obj.Limit)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ConsumeEventsPermissioned) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Limit`:
	err = decoder.Decode(&obj.Limit)
	if err != nil {
		return err
	}
	return nil
}

// NewConsumeEventsPermissionedInstruction declares a new ConsumeEventsPermissioned instruction with the provided parameters and accounts.
func NewConsumeEventsPermissionedInstruction(
	// Parameters:
	limit uint16,
	// Accounts:
	openOrders ag_solanago.PublicKey,
	market ag_solanago.PublicKey,
	eventQueue ag_solanago.PublicKey,
	crankAuthority ag_solanago.PublicKey) *ConsumeEventsPermissioned {
	return NewConsumeEventsPermissionedInstructionBuilder().
		SetLimit(limit).
		SetOpenOrdersAccount(openOrders).
		SetMarketAccount(market).
		SetEventQueueAccount(eventQueue).
		SetCrankAuthorityAccount(crankAuthority)
}
