// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package serum_dex

import (
	"bytes"
	"strconv"
	"testing"

	ag_gofuzz "github.com/gagliardetto/gofuzz"
	ag_require "github.com/stretchr/testify/require"
)

func TestEncodeDecode_ConsumeEvents(t *testing.T) {
	fu := ag_gofuzz.New().NilChance(0)
	for i := 0; i < 1; i++ {
		t.Run("ConsumeEvents"+strconv.Itoa(i), func(t *testing.T) {
			{
				params := new(ConsumeEvents)
				fu.Fuzz(params)
				params.OpenOrders = nil
				params.OtherAccounts = nil
				buf := new(bytes.Buffer)
				err := encodeT(*params, buf)
				ag_require.NoError(t, err)
				//
				got := new(ConsumeEvents)
				err = decodeT(got, buf.Bytes())
				got.OpenOrders = nil
				got.OtherAccounts = nil
				ag_require.NoError(t, err)
				ag_require.Equal(t, params, got)
			}
		})
	}
}
